<a href="https://colab.research.google.com/github/aqafridi/TensorFlow/blob/main/Tensorflow_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Single Neuron

In [24]:
from tensorflow import keras
import numpy as np
model=keras.Sequential([keras.layers.Dense(units=1,input_shape=[1])])
model.compile(optimizer='adam',loss='mean_squared_error')
xs = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], dtype=float)
ys = np.array([2.0, 4.0, 6.0, 8.0, 10.0, 12.0], dtype=float)
model.fit(xs,ys,epochs=5000,verbose=False)

In [4]:
model.predict([10])

array([[19.999994]], dtype=float32)

#multiple neuron

In [21]:
from tensorflow import keras
import numpy as np
model=keras.Sequential([keras.layers.Dense(units=1,input_shape=[1]),
                        keras.layers.Dense(units=10),keras.layers.Dense(units=1)])
model.compile(optimizer='adam',loss='mean_squared_error')
xs = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], dtype=float)
ys = np.array([2.0, 4.0, 6.0, 8.0, 10.0, 12.0], dtype=float)
model.fit(xs,ys,epochs=5000,verbose=False)
test_loss = model.evaluate(xs, ys)

1/1 [==============================] - 0s 63ms/step - loss: 1.5916e-12


In [6]:
model.predict([10])

array([[19.998728]], dtype=float32)

#Computer Vision

In [16]:
from tensorflow import keras
(x_train,y_train),(x_test,y_test)=keras.datasets.fashion_mnist.load_data()
model=keras.Sequential([keras.layers.Flatten(input_shape=(28,28)),
                        keras.layers.Dense(units=128,activation='relu'),
                        keras.layers.Dense(units=10,activation='softmax')
                        ])
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=10, verbose=False)
test_loss = model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.8282


In [38]:
img=x_test[1004]
img = img.reshape(1, 784)
model.predict(img)

array([[0.10656185, 0.10638779, 0.10708158, 0.10709922, 0.10708805,
        0.03853885, 0.10726833, 0.10674466, 0.10734092, 0.10588875]],
      dtype=float32)

#Callbacks

In [17]:
import tensorflow as tf
from tensorflow import keras
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('loss')<0.4):
      print("\nReached 60% accuracy so cancelling training!")
      self.model.stop_training = True

callbacks = myCallback()
(x_train,y_train),(x_test,y_test)=keras.datasets.fashion_mnist.load_data()
model=keras.Sequential([keras.layers.Flatten(input_shape=(28,28)),
                        keras.layers.Dense(units=512,activation='relu'),
                        keras.layers.Dense(units=10,activation='softmax')
                        ])
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=10, callbacks=[callbacks],verbose=False)
test_loss = model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.8370


#CNN

In [18]:
from tensorflow import keras
(x_train,y_train),(x_test,y_test)=keras.datasets.cifar10.load_data()
model=keras.Sequential([keras.layers.Conv2D(filters=64,kernel_size=(3,3),input_shape=(32,32,3),activation='relu'),
                        keras.layers.MaxPool2D(pool_size=(2,2)),
                        keras.layers.Conv2D(64,(3,3),activation='relu'),
                        keras.layers.MaxPool2D(pool_size=(2,2)),
                        keras.layers.Flatten(),
                        keras.layers.Dense(units=512,activation='relu'),
                        keras.layers.Dense(units=10,activation='softmax')
                        ])
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=3,verbose=False)
test_loss = model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 1.4592 - accuracy: 0.4749


In [11]:
import tensorflow as tf
mnist = tf.keras.datasets.fashion_mnist
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()
training_images=training_images.reshape(60000, 28, 28, 1)
training_images=training_images / 255.0
test_images = test_images.reshape(10000, 28, 28, 1)
test_images=test_images/255.0
model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(64, (3,3), activation='relu', input_shape=(28, 28, 1)),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2,2),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(10, activation='softmax')
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# model.summary()
model.fit(training_images, training_labels, epochs=5,verbose=False)
test_loss = model.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 2ms/step - loss: 0.2708 - accuracy: 0.9059


In [13]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()
training_images=training_images.reshape(60000, 28, 28, 1)
training_images=training_images / 255.0
test_images = test_images.reshape(10000, 28, 28, 1)
test_images=test_images/255.0
model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(28, 28, 1)),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(10, activation='softmax')
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(training_images, training_labels, epochs=10,verbose=False)
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(test_acc)

2.4.1
313/313 [==============================] - 1s 2ms/step - loss: 0.0554 - accuracy: 0.9865
0.9865000247955322


#Real-world Images
##image generator

In [ ]:
from tensorflow import keras
import tensorflow as tf
train_datagen=keras.preprocessing.image.ImageDataGenerator(rescale=1./255)
train_generator=train_datagen.flow_from_directory(
    train_dir,target_size=(300,300,3),batch_size=128,classmode='binary')

test_gene=keras.preprocessing.image.ImageDataGenerator(rescale=1./255)
validation_generator=test_gene.flow_from_directory(
    valid_dir,target_size=(300,300,3),batch_size=32,classmode='binary')

model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(16, (3,3), activation='relu', input_shape=(300, 300, 3)),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2,2),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation='relu'),
  tf.keras.layers.Dense(1, activation='sigmoid')
])

history=model.fit_generator(train_generator,steps_per_epoch=8,epochs=5,
                            validation_data=validation_generator,
                            validation_steps=8,verbose=2)

