<a href="https://colab.research.google.com/github/aqafridi/TensorFlow/blob/main/Tensorflow_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Single Neuron

In [3]:
from tensorflow import keras
import numpy as np
model=keras.Sequential([keras.layers.Dense(units=1,input_shape=[1])])
model.compile(optimizer='adam',loss='mean_squared_error')
xs = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], dtype=float)
ys = np.array([2.0, 4.0, 6.0, 8.0, 10.0, 12.0], dtype=float)
model.fit(xs,ys,epochs=5000,verbose=False)

In [4]:
model.predict([10])

array([[19.999994]], dtype=float32)

#multiple neuron

In [5]:
from tensorflow import keras
import numpy as np
model=keras.Sequential([keras.layers.Dense(units=1,input_shape=[1]),
                        keras.layers.Dense(units=10),keras.layers.Dense(units=1)])
model.compile(optimizer='adam',loss='mean_squared_error')
xs = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], dtype=float)
ys = np.array([2.0, 4.0, 6.0, 8.0, 10.0, 12.0], dtype=float)
model.fit(xs,ys,epochs=5000,verbose=False)

In [6]:
model.predict([10])

array([[19.998728]], dtype=float32)

#Conv Vision

In [30]:
from tensorflow import keras
(x_train,y_train),(x_test,y_test)=keras.datasets.fashion_mnist.load_data()
model=keras.Sequential([keras.layers.Flatten(input_shape=(28,28)),
                        keras.layers.Dense(units=128,activation='relu'),
                        keras.layers.Dense(units=10,activation='softmax')
                        ])
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy')
model.fit(x_train,y_train,epochs=10, verbose=False)

In [38]:
img=x_test[1004]
img = img.reshape(1, 784)
model.predict(img)

array([[0.10656185, 0.10638779, 0.10708158, 0.10709922, 0.10708805,
        0.03853885, 0.10726833, 0.10674466, 0.10734092, 0.10588875]],
      dtype=float32)

#Callbacks

In [39]:
import tensorflow as tf
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('loss')<0.4):
      print("\nReached 60% accuracy so cancelling training!")
      self.model.stop_training = True

callbacks = myCallback()
(x_train,y_train),(x_test,y_test)=keras.datasets.fashion_mnist.load_data()
model=keras.Sequential([keras.layers.Flatten(input_shape=(28,28)),
                        keras.layers.Dense(units=128,activation='relu'),
                        keras.layers.Dense(units=10,activation='softmax')
                        ])
model.compile(optimizer='sgd',loss='sparse_categorical_crossentropy')
model.fit(x_train,y_train,epochs=10, callbacks=[callbacks],verbose=False)